language: python
matrix:
    include:
        - python: "2.7"
          env: TOXENV=lint
          #env: TOXENV=py27
        - python: "3.6"
          env: TOXENV=lint
install: pip install -U tox coveralls
script: tox
after_success: coveralls
